import json
from datetime import date, datetime
from pathlib import Path
from zoneinfo import ZoneInfo

from google.cloud import bigquery


PROJECT_ID = "music-analytics-500503"
DATASET_ID = "artist_momentum_raw"
TABLE_ID = "raw_apple_chart_entries"

PROCESSED_DIR = Path("data/processed")

REPORTING_TIMEZONE = ZoneInfo("America/Chicago")


def get_latest_processed_file() -> Path:
    """
    Used when this script is run manually from the terminal.

    Dagster will pass the exact processed file path directly instead.
    """
    files = list(
        PROCESSED_DIR.glob("apple_chart_entries_*.jsonl")
    )

    if not files:
        raise FileNotFoundError(
            "No processed Apple chart JSONL files found "
            "in data/processed."
        )

    return max(
        files,
        key=lambda path: path.stat().st_mtime,
    )


def read_jsonl(file_path: Path) -> list[dict]:
    rows = []

    with file_path.open(
        "r",
        encoding="utf-8",
    ) as f:
        for line in f:
            if line.strip():
                rows.append(
                    json.loads(line)
                )

    return rows


def get_snapshot_date(
    ingested_at: str,
) -> date:
    """
    Convert the UTC ingestion timestamp into the
    reporting date used by this project.

    The project uses America/Chicago so that one
    scheduled daily run maps to one local calendar day.
    """
    ingested_datetime = datetime.fromisoformat(
        ingested_at.replace(
            "Z",
            "+00:00",
        )
    )

    if ingested_datetime.tzinfo is None:
        raise ValueError(
            "ingested_at must contain timezone information."
        )

    return ingested_datetime.astimezone(
        REPORTING_TIMEZONE
    ).date()


def snapshot_already_loaded(
    client: bigquery.Client,
    full_table_id: str,
    country: str,
    chart_type: str,
    snapshot_date: date,
) -> bool:
    """
    Prevent more than one chart snapshot from being loaded
    for the same reporting day.

    One daily snapshot is uniquely identified by:

        country
        + chart_type
        + America/Chicago calendar date

    This makes retries and accidental manual reruns
    idempotent even if Apple's feed_updated value changes.
    """
    query = f"""
        select count(*) as row_count
        from `{full_table_id}`
        where country = @country
          and chart_type = @chart_type
          and date(
                safe_cast(ingested_at as timestamp),
                "America/Chicago"
              ) = @snapshot_date
    """

    job_config = bigquery.QueryJobConfig(
        query_parameters=[
            bigquery.ScalarQueryParameter(
                "country",
                "STRING",
                country,
            ),
            bigquery.ScalarQueryParameter(
                "chart_type",
                "STRING",
                chart_type,
            ),
            bigquery.ScalarQueryParameter(
                "snapshot_date",
                "DATE",
                snapshot_date,
            ),
        ]
    )

    result = client.query(
        query,
        job_config=job_config,
    ).result()

    row = next(result)

    return row.row_count > 0


def get_table_row_count(
    client: bigquery.Client,
    full_table_id: str,
) -> int:
    query = f"""
        select count(*) as row_count
        from `{full_table_id}`
    """

    result = client.query(
        query
    ).result()

    row = next(result)

    return row.row_count


def load_jsonl_to_bigquery(
    client: bigquery.Client,
    file_path: Path,
    full_table_id: str,
) -> None:
    job_config = bigquery.LoadJobConfig(
        source_format=(
            bigquery.SourceFormat.NEWLINE_DELIMITED_JSON
        ),
        write_disposition=(
            bigquery.WriteDisposition.WRITE_APPEND
        ),
    )

    with file_path.open(
        "rb",
    ) as f:
        load_job = client.load_table_from_file(
            f,
            full_table_id,
            job_config=job_config,
        )

    load_job.result()


def load_apple_chart_to_bigquery(
    processed_file_path: str | Path,
) -> dict:
    """
    Load one specific processed Apple Music chart file
    into BigQuery.

    Dagster passes the exact JSONL file generated by the
    normalization asset.

    Only one snapshot is loaded per America/Chicago
    calendar day.

    Returns metadata describing what happened during the load.
    """
    processed_file_path = Path(
        processed_file_path
    )

    if not processed_file_path.exists():
        raise FileNotFoundError(
            "Processed Apple chart file does not exist: "
            f"{processed_file_path}"
        )

    rows = read_jsonl(
        processed_file_path
    )

    if not rows:
        raise ValueError(
            f"No rows found in {processed_file_path}"
        )

    first_row = rows[0]

    country = first_row["country"]
    chart_type = first_row["chart_type"]
    feed_updated = first_row["feed_updated"]
    ingested_at = first_row["ingested_at"]

    snapshot_date = get_snapshot_date(
        ingested_at
    )

    full_table_id = (
        f"{PROJECT_ID}."
        f"{DATASET_ID}."
        f"{TABLE_ID}"
    )

    client = bigquery.Client(
        project=PROJECT_ID
    )

    print(
        f"Processed file: {processed_file_path}"
    )

    print(
        f"Rows in file: {len(rows)}"
    )

    print(
        f"Target table: {full_table_id}"
    )

    print(
        "Snapshot: "
        f"country={country}, "
        f"chart_type={chart_type}, "
        f"snapshot_date={snapshot_date}, "
        f"feed_updated={feed_updated}"
    )

    if snapshot_already_loaded(
        client=client,
        full_table_id=full_table_id,
        country=country,
        chart_type=chart_type,
        snapshot_date=snapshot_date,
    ):
        print(
            f"A snapshot for {snapshot_date} "
            "already exists in BigQuery. "
            "No rows were loaded."
        )

        return {
            "loaded": False,
            "rows_added": 0,
            "rows_in_file": len(rows),
            "table": full_table_id,
            "country": country,
            "chart_type": chart_type,
            "feed_updated": feed_updated,
            "snapshot_date": (
                snapshot_date.isoformat()
            ),
        }

    before_count = get_table_row_count(
        client,
        full_table_id,
    )

    load_jsonl_to_bigquery(
        client=client,
        file_path=processed_file_path,
        full_table_id=full_table_id,
    )

    after_count = get_table_row_count(
        client,
        full_table_id,
    )

    rows_added = (
        after_count - before_count
    )

    print("Load complete.")
    print(
        f"Rows before: {before_count}"
    )
    print(
        f"Rows after: {after_count}"
    )
    print(
        f"Rows added: {rows_added}"
    )

    return {
        "loaded": True,
        "rows_added": rows_added,
        "rows_in_file": len(rows),
        "table": full_table_id,
        "country": country,
        "chart_type": chart_type,
        "feed_updated": feed_updated,
        "snapshot_date": (
            snapshot_date.isoformat()
        ),
    }


def main() -> None:
    """
    Preserve the manual command-line behavior.

    Running:

        python scripts/load_apple_charts_to_bigquery.py

    still loads the newest processed JSONL file.
    """
    latest_file = (
        get_latest_processed_file()
    )

    load_apple_chart_to_bigquery(
        latest_file
    )


if __name__ == "__main__":
    main()